
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150226 (SVN rev 63)
//----------------------------------------------------

package ParserUFE;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFIER = 79;
  public static final int TEXTFIELD_O = 27;
  public static final int FROM = 7;
  public static final int RENDER = 3;
  public static final int CUSTOM_O = 45;
  public static final int SPINNER_O = 30;
  public static final int ITEM_O = 33;
  public static final int TEXTFIELD_C = 37;
  public static final int LESS_EQ = 64;
  public static final int CUSTOM_C = 46;
  public static final int SPINNER_C = 40;
  public static final int ITEM_C = 43;
  public static final int C_CURLY = 50;
  public static final int SI = 8;
  public static final int COMMA = 53;
  public static final int DOUBLE_LITERAL = 73;
  public static final int POW = 61;
  public static final int O_PAREN = 47;
  public static final int GREATER_EQ = 65;
  public static final int O_BOX = 51;
  public static final int DEFAULT_O = 34;
  public static final int INTEGER_LITERAL = 74;
  public static final int NOT = 71;
  public static final int DEFAULT_C = 44;
  public static final int VAR = 2;
  public static final int MIN = 22;
  public static final int C_PAREN = 48;
  public static final int WIDTH = 17;
  public static final int EQ = 55;
  public static final int BOOLEAN_LITERAL = 76;
  public static final int ELEMENTS_O = 32;
  public static final int COLOR_LITERAL = 77;
  public static final int ELEMENTS_C = 42;
  public static final int PLUS = 57;
  public static final int C_BOX = 52;
  public static final int EQ_EQ = 66;
  public static final int Y = 15;
  public static final int X = 14;
  public static final int IMPRIMIR = 12;
  public static final int GREATER = 63;
  public static final int DIV = 60;
  public static final int MAX = 23;
  public static final int RETURN = 4;
  public static final int MULT = 59;
  public static final int IMAGE_O = 31;
  public static final int STRING_LITERAL = 72;
  public static final int IMAGE_C = 41;
  public static final int EOF = 0;
  public static final int MIENTRAS = 11;
  public static final int SEMICOLON = 54;
  public static final int IMPORT = 6;
  public static final int CLASSNAME = 20;
  public static final int MINUS = 58;
  public static final int SRC = 24;
  public static final int BUTTON_O = 28;
  public static final int OR = 69;
  public static final int error = 1;
  public static final int LIST_O = 29;
  public static final int ID = 13;
  public static final int COLOR = 18;
  public static final int BUTTON_C = 38;
  public static final int SINO = 9;
  public static final int PANEL_O = 25;
  public static final int LIST_C = 39;
  public static final int NOT_EQ = 67;
  public static final int PLAIN_TEXT = 78;
  public static final int CHARACTER_LITERAL = 75;
  public static final int BORDER = 19;
  public static final int HEIGHT = 16;
  public static final int PANEL_C = 35;
  public static final int TEXT_O = 26;
  public static final int ONCLICK = 21;
  public static final int LESS = 62;
  public static final int COMPONENT = 5;
  public static final int AND = 68;
  public static final int UMINUS = 56;
  public static final int TEXT_C = 36;
  public static final int XOR = 70;
  public static final int REPETIR = 10;
  public static final int O_CURLY = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "RENDER",
  "RETURN",
  "COMPONENT",
  "IMPORT",
  "FROM",
  "SI",
  "SINO",
  "REPETIR",
  "MIENTRAS",
  "IMPRIMIR",
  "ID",
  "X",
  "Y",
  "HEIGHT",
  "WIDTH",
  "COLOR",
  "BORDER",
  "CLASSNAME",
  "ONCLICK",
  "MIN",
  "MAX",
  "SRC",
  "PANEL_O",
  "TEXT_O",
  "TEXTFIELD_O",
  "BUTTON_O",
  "LIST_O",
  "SPINNER_O",
  "IMAGE_O",
  "ELEMENTS_O",
  "ITEM_O",
  "DEFAULT_O",
  "PANEL_C",
  "TEXT_C",
  "TEXTFIELD_C",
  "BUTTON_C",
  "LIST_C",
  "SPINNER_C",
  "IMAGE_C",
  "ELEMENTS_C",
  "ITEM_C",
  "DEFAULT_C",
  "CUSTOM_O",
  "CUSTOM_C",
  "O_PAREN",
  "C_PAREN",
  "O_CURLY",
  "C_CURLY",
  "O_BOX",
  "C_BOX",
  "COMMA",
  "SEMICOLON",
  "EQ",
  "UMINUS",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "POW",
  "LESS",
  "GREATER",
  "LESS_EQ",
  "GREATER_EQ",
  "EQ_EQ",
  "NOT_EQ",
  "AND",
  "OR",
  "XOR",
  "NOT",
  "STRING_LITERAL",
  "DOUBLE_LITERAL",
  "INTEGER_LITERAL",
  "CHARACTER_LITERAL",
  "BOOLEAN_LITERAL",
  "COLOR_LITERAL",
  "PLAIN_TEXT",
  "IDENTIFIER"
  };

  /* non terminals */
  static final int text_field = 44;
  static final int comp = 41;
  static final int list_default = 54;
  static final int list_cnt$ = 53;
  static final int ulogic_expr = 18;
  static final int decl_item = 26;
  static final int biconcat_expr = 23;
  static final int image = 48;
  static final int _return = 34;
  static final int else_content = 31;
  static final int block = 28;
  static final int array_decl = 11;
  static final int l_glob = 2;
  static final int l_comps$ = 36;
  static final int embedded_ufe = 55;
  static final int panel = 42;
  static final int biarith_expr = 22;
  static final int bicomp_expr = 20;
  static final int button = 45;
  static final int prop = 39;
  static final int l_comps = 35;
  static final int list = 46;
  static final int atomic_expr = 17;
  static final int custom = 49;
  static final int cnt_l = 51;
  static final int cnt_group = 50;
  static final int glob = 1;
  static final int text = 43;
  static final int l_expr = 24;
  static final int prop_value = 40;
  static final int repeat = 32;
  static final int render = 5;
  static final int component_def = 6;
  static final int bilogic_expr = 21;
  static final int spinner = 47;
  static final int array_assign = 13;
  static final int _if = 29;
  static final int id_expr = 15;
  static final int _while = 33;
  static final int _if_else = 30;
  static final int l_stmts$ = 8;
  static final int list_cnt = 52;
  static final int l_stmts = 7;
  static final int s = 0;
  static final int uarith_expr = 19;
  static final int l_props = 37;
  static final int expr = 14;
  static final int css_import = 4;
  static final int assign = 12;
  static final int print = 27;
  static final int decl = 10;
  static final int l_decl_items = 25;
  static final int ufe_import = 3;
  static final int l_props$ = 38;
  static final int stmt = 9;
  static final int arrayindex_expr = 16;
}

