
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150226 (SVN rev 63)
//----------------------------------------------------

package ParserHTML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIV_O = 7;
  public static final int BODY_O = 5;
  public static final int HTML_O = 2;
  public static final int NOUFE_O = 6;
  public static final int DIV_C = 13;
  public static final int TITLE_O = 4;
  public static final int BODY_C = 11;
  public static final int HTML_C = 8;
  public static final int NOUFE_C = 12;
  public static final int EOF = 0;
  public static final int TITLE_C = 10;
  public static final int HEAD_O = 3;
  public static final int error = 1;
  public static final int PLAIN_TEXT = 14;
  public static final int HEAD_C = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HTML_O",
  "HEAD_O",
  "TITLE_O",
  "BODY_O",
  "NOUFE_O",
  "DIV_O",
  "HTML_C",
  "HEAD_C",
  "TITLE_C",
  "BODY_C",
  "NOUFE_C",
  "DIV_C",
  "PLAIN_TEXT"
  };

  /* non terminals */
  static final int l_html_cnt = 1;
  static final int l_plaintext$ = 6;
  static final int body = 3;
  static final int l_body_cnt = 4;
  static final int html_cnt = 2;
  static final int l_plaintext = 5;
  static final int s = 0;
}

