
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150226 (SVN rev 63)
//----------------------------------------------------

package ParserCSS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int C_PAREN = 15;
  public static final int FONT_COLOR = 11;
  public static final int SEMICOLON = 18;
  public static final int BOOL_LITERAL = 25;
  public static final int C_CURLY = 17;
  public static final int RGB = 12;
  public static final int COLOR_NAME = 13;
  public static final int BORDER_WIDTH = 7;
  public static final int WIDTH = 3;
  public static final int BORDER_COLOR = 6;
  public static final int IDENTIFIER = 27;
  public static final int ALIGN = 8;
  public static final int COLON = 21;
  public static final int ALIGN_LITERAL = 26;
  public static final int STRING_LITERAL = 22;
  public static final int COMMA = 19;
  public static final int EOF = 0;
  public static final int NUMBER_LITERAL = 23;
  public static final int HEIGHT = 2;
  public static final int DOT = 20;
  public static final int error = 1;
  public static final int O_PAREN = 14;
  public static final int BORDER = 5;
  public static final int HEX_COLOR = 24;
  public static final int FONT_SIZE = 10;
  public static final int O_CURLY = 16;
  public static final int FONT = 9;
  public static final int BACKGROUND = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HEIGHT",
  "WIDTH",
  "BACKGROUND",
  "BORDER",
  "BORDER_COLOR",
  "BORDER_WIDTH",
  "ALIGN",
  "FONT",
  "FONT_SIZE",
  "FONT_COLOR",
  "RGB",
  "COLOR_NAME",
  "O_PAREN",
  "C_PAREN",
  "O_CURLY",
  "C_CURLY",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "COLON",
  "STRING_LITERAL",
  "NUMBER_LITERAL",
  "HEX_COLOR",
  "BOOL_LITERAL",
  "ALIGN_LITERAL",
  "IDENTIFIER"
  };

  /* non terminals */
  static final int l_subclasses = 6;
  static final int color_value = 9;
  static final int subclass = 4;
  static final int l_properties = 7;
  static final int _class = 3;
  static final int l_subclasses_ = 5;
  static final int l_subproperties = 8;
  static final int property = 1;
  static final int l_classes = 2;
  static final int s = 0;
}

